---
- name: installing package for python env
  ansible.builtin.package:
    name:
      - python3-pip
    update_cache: yes
- name: Create Dir
  ansible.builtin.file:
    path: ./basic-http-server
    state: directory
- name: install apache2
  ansible.builtin.package:
    name: apache2
    update_cache: yes
    state: latest
        