---
- name: installing package for python env
  ansible.builtin.package:
    name:
      - python3-pip
    update_cache: yes



















# - name: Create Dir
#   ansible.builtin.file:
#     path: ./djangoapp
#     state: directory

    
# - name: install venv
#   command:
#     cmd: python3 -m pip install --user virtualenv
   

# - name: createvenv
#   command:
#     cmd: python3 -m venv .venv
#     path: ./djangoapp

# - name: activate vm
#   command:
#     cmd: source .venv/bin/activate

# - name: install django
#   ansible.builtin.pip:
#     name:
#       - django


