---
- name: installing package for python env
  become: true
  apt:
    name:
      - python3-pip
    update_cache: yes
- name: Create Dir
  file:
    path: ./basic-http-server
    state: directory
- name: install apache2
  apt:
    name: apache2
    update_cache: yes
    state: latest
        