---
- name: Pull Django app from docker hub
  community.docker.docker_image_pull:
    name: tahaefazati/mysite_backend
    tag: latest
    pull: always
    

- name: create django app container
  community.docker.docker_container:
    name: myapp
    image: tahaefazati/mysite_backend:latest
    state: started
    ports:
      - "8080:8000"
    # networks: 
    #   name: "{{ docker_network_name }}"